spin_manifest_version = 2

[application]
name = "my-app"
version = "0.1.0"
authors = ["Ryan Levick <ryan.levick@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "my-app"

[component.my-app]
source = "app.wasm"
allowed_outbound_hosts = ["https://my.api.com"]
key_value_stores = ["cache"]
[component.my-app.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["app.py", "Pipfile"]
[component.my-app.tool.spin-test]
source = "../../test-rs/target/wasm32-wasip1/release/wasm_test.wasm"
build = "cargo component build --release --target-dir=target"
workdir = "../../test-rs"
